package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.orderDO;
import org.apache.ibatis.annotations.Param;

public interface orderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed May 29 20:56:53 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed May 29 20:56:53 CST 2019
     */
    int insert(orderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed May 29 20:56:53 CST 2019
     */
    int insertSelective(orderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed May 29 20:56:53 CST 2019
     */
    orderDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed May 29 20:56:53 CST 2019
     */
    int updateByPrimaryKeySelective(orderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed May 29 20:56:53 CST 2019
     */
    int updateByPrimaryKey(orderDO record);


}