package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.sequenceDO;

public interface sequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed May 29 22:24:57 CST 2019
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed May 29 22:24:57 CST 2019
     */
    int insert(sequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed May 29 22:24:57 CST 2019
     */
    int insertSelective(sequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed May 29 22:24:57 CST 2019
     */
    sequenceDO selectByPrimaryKey(String name);

    sequenceDO getSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed May 29 22:24:57 CST 2019
     */
    int updateByPrimaryKeySelective(sequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed May 29 22:24:57 CST 2019
     */
    int updateByPrimaryKey(sequenceDO record);
}